services:
  - type: web
    name: faceswap-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      mkdir -p models
      wget https://huggingface.co/deepinsight/insightface/resolve/main/models/inswapper_128.onnx -O models/inswapper_128.onnx
      python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000 