services:
  - type: web
    name: faceswap-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        g++ \
        libgl1-mesa-glx \
        libglib2.0-0 \
      && rm -rf /var/lib/apt/lists/*
      mkdir -p models
      pip install -r requirements.txt
    startCommand: |
      mkdir -p models
      python download_model.py
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: HF_TOKEN
        sync: false
    disk:
      name: models
      mountPath: /models
      sizeGB: 1 